# -*- coding: utf-8 -*-
"""8.7f1test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17cDe2DS_rTeUWR5czHkza3Y8a6xRXVYQ
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install deeplabcut

import deeplabcut

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Deeplabcut/test2-ruoqi-2023-08-04
! ls

config_path = "/content/drive/MyDrive/Colab Deeplabcut/test2-ruoqi-2023-08-04/config.yaml"

deeplabcut.check_labels(config_path)

deeplabcut.create_training_dataset(config_path, num_shuffles=1)

deeplabcut.train_network(config_path,shuffle=1, displayiters=100,saveiters=500, maxiters=20000)

# Commented out IPython magic to ensure Python compatibility.
#  %matplotlib notebook
 deeplabcut.evaluate_network(config_path, plotting=True)

!pip install tables==3.7.0

deeplabcut.analyze_videos(config_path,['/content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos'], save_as_csv=True, videotype='.mp4')

deeplabcut.create_labeled_video(config_path,['/content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos/f2.mp4'])

deeplabcut.create_labeled_video(config_path,['/content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos'],save_frames=True)
